version: '3'

networks:
  inception_network:

secrets:
  secrets_env:
    file: .env

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    build:
      context: requirements/mariadb
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT: "${MYSQL_ROOT}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - mariadb-volume:/var/lib/mysql
    networks:
      - inception_network
    secrets:
      - secrets_env

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    build:
      context: requirements/wordpress
    depends_on:
      - mariadb
    environment:
      WP_DATABASE: "${MYSQL_DATABASE}"
      WP_DB_USER: "${MYSQL_USER}"
      WP_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WP_USER: "${WP_USER}"
      WP_PASSWORD: "${WP_PASSWORD}"
      WP_ROOT: "${WP_ROOT}"
      WP_ROOT_PASSWORD: "${WP_ROOT_PASSWORD}"
      WP_DATABASE_HOST: "mariadb"
    volumes:
      - wordpress-volume:/var/www/wordpress
    networks:
      - inception_network
    secrets:
      - secrets_env

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    depends_on:
      - wordpress
    build: requirements/nginx
    volumes:
      - wordpress-volume:/var/www/wordpress
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf      
    networks:
      - inception_network
    ports:
      - 443:443

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rleslie-/data/mariadb
    
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rleslie-/data/wordpress